(()=> {
const q=s=>document.querySelector(s), qa=(s,root=document)=>[...root.querySelectorAll(s)];
const nav=q('#hytNav'); addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>40),{passive:true});
const MAPS_ENDPOINT=(window.ASWAL_CONFIG?.mapsProxy||document.documentElement.dataset.mapsProxy||'').replace(/\/$/,'');
const legacyKm={kedarnath:410,badrinath:325,yamunotri:230,gangotri:290,vrindavan:250,delhi:220,ayodhya:550,varanasi:700,jaipur:600};
const legacyNames={kedarnath:'Kedarnath',badrinath:'Badrinath',yamunotri:'Yamunotri',gangotri:'Gangotri',vrindavan:'Vrindavan',delhi:'Delhi',ayodhya:'Ayodhya',varanasi:'Varanasi',jaipur:'Jaipur'};
const vehicleCatalog=[
{id:'force-traveller-9',manufacturer:'Force',model:'Traveller N 3050WB',full_name:'Force Traveller N 3050WB — 9 Seater',category:'Tempo Traveller',seating_capacity:9,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:32,minimum_booking_rate:4500,active:true,aliases:['traveller','tempo','9 seater']},
{id:'force-traveller-12',manufacturer:'Force',model:'Traveller N 3350WB',full_name:'Force Traveller N 3350WB — 12 Seater',category:'Tempo Traveller',seating_capacity:12,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:35,minimum_booking_rate:5000,active:true,aliases:['traveller','tempo','12 seater']},
{id:'force-traveller-16',manufacturer:'Force',model:'Traveller N 4020WB',full_name:'Force Traveller N 4020WB — 16 Seater',category:'Tempo Traveller',seating_capacity:16,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:38,minimum_booking_rate:6000,active:true,aliases:['traveller','tempo','16 seater']},
{id:'force-traveller-17',manufacturer:'Force',model:'Traveller N 3700WB',full_name:'Force Traveller N 3700WB — 17 Seater',category:'Tempo Traveller',seating_capacity:17,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:40,minimum_booking_rate:6500,active:true,aliases:['traveller','tempo','17 seater']},
{id:'force-traveller-20',manufacturer:'Force',model:'Traveller N Wider Body 4020WB',full_name:'Force Traveller N Wider Body 4020WB — 20 Seater',category:'Tempo Traveller',seating_capacity:20,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Large',per_km_rate:44,minimum_booking_rate:7500,active:true,aliases:['traveller','tempo','20 seater']},
{id:'force-urbania-12',manufacturer:'Force',model:'Urbania DX 3615WB',full_name:'Force Urbania DX 3615WB — 12 Seater',category:'Luxury Traveller',seating_capacity:12,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Large',per_km_rate:52,minimum_booking_rate:9000,active:true,aliases:['urbania','luxury traveller']},
{id:'toyota-innova-crysta',manufacturer:'Toyota',model:'Innova Crysta',full_name:'Toyota Innova Crysta — 7/8 Seater',category:'Innova Crysta',seating_capacity:8,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:27,minimum_booking_rate:4500,active:true,aliases:['innova','crysta']},
{id:'toyota-innova-hycross',manufacturer:'Toyota',model:'Innova HyCross',full_name:'Toyota Innova HyCross — 7/8 Seater',category:'Innova',seating_capacity:8,fuel_type:'Petrol / Hybrid',transmission:'Automatic',luggage_capacity:'Standard',per_km_rate:30,minimum_booking_rate:5000,active:true,aliases:['innova','hycross']},
{id:'mahindra-scorpio-classic',manufacturer:'Mahindra',model:'Scorpio Classic',full_name:'Mahindra Scorpio Classic — 7 Seater',category:'SUV',seating_capacity:7,fuel_type:'Diesel',transmission:'Manual',luggage_capacity:'Standard',per_km_rate:25,minimum_booking_rate:4500,active:true,aliases:['scorpio','scor']},
{id:'mahindra-scorpio-n',manufacturer:'Mahindra',model:'Scorpio-N',full_name:'Mahindra Scorpio-N — 7 Seater',category:'Premium SUV',seating_capacity:7,fuel_type:'Petrol / Diesel',transmission:'Manual / Automatic',luggage_capacity:'Standard',per_km_rate:30,minimum_booking_rate:5000,active:true,aliases:['scorpio','scor']},
{id:'mahindra-xuv-7xo',manufacturer:'Mahindra',model:'XUV 7XO',full_name:'Mahindra XUV 7XO — 7 Seater',category:'Premium SUV',seating_capacity:7,fuel_type:'Petrol / Diesel',transmission:'Manual / Automatic',luggage_capacity:'Standard',per_km_rate:32,minimum_booking_rate:5500,active:true,aliases:['xuv','xuv700']},
{id:'mahindra-xuv-3xo',manufacturer:'Mahindra',model:'XUV 3XO',full_name:'Mahindra XUV 3XO — 5 Seater',category:'SUV',seating_capacity:5,fuel_type:'Petrol / Diesel / EV',transmission:'Manual / Automatic',luggage_capacity:'Standard',per_km_rate:22,minimum_booking_rate:4000,active:true,aliases:['xuv','3xo']},
{id:'sedan',manufacturer:'Multi-brand',model:'Sedan',full_name:'Sedan — 4 Seater',category:'Sedan',seating_capacity:4,fuel_type:'Diesel / Petrol',transmission:'Manual / Automatic',luggage_capacity:'Standard',per_km_rate:15,minimum_booking_rate:3000,active:true,aliases:['car','sedan']},
{id:'suv',manufacturer:'Multi-brand',model:'SUV',full_name:'SUV — 6/7 Seater',category:'SUV',seating_capacity:7,fuel_type:'Diesel / Petrol',transmission:'Manual / Automatic',luggage_capacity:'Standard',per_km_rate:19,minimum_booking_rate:3500,active:true,aliases:['car','suv']}
];
const fallbackLocations=[
['Haridwar','Uttarakhand'],['Rishikesh','Uttarakhand'],['Dehradun','Uttarakhand'],['Mussoorie','Uttarakhand'],['Kedarnath','Uttarakhand'],['Badrinath','Uttarakhand'],['Gangotri','Uttarakhand'],['Yamunotri','Uttarakhand'],['Delhi','Delhi'],['Agra','Uttar Pradesh'],['Mathura','Uttar Pradesh'],['Vrindavan','Uttar Pradesh'],['Lucknow','Uttar Pradesh'],['Ayodhya','Uttar Pradesh'],['Varanasi','Uttar Pradesh'],['Prayagraj','Uttar Pradesh'],['Noida','Uttar Pradesh'],['Meerut','Uttar Pradesh'],['Jaipur','Rajasthan'],['Udaipur','Rajasthan'],['Jodhpur','Rajasthan'],['Kota','Rajasthan'],['Ajmer','Rajasthan'],['Mumbai','Maharashtra'],['Pune','Maharashtra'],['Nashik','Maharashtra'],['Nagpur','Maharashtra'],['Shirdi','Maharashtra'],['Ahmedabad','Gujarat'],['Surat','Gujarat'],['Vadodara','Gujarat'],['Rajkot','Gujarat'],['Dwarka','Gujarat'],['Chennai','Tamil Nadu'],['Madurai','Tamil Nadu'],['Coimbatore','Tamil Nadu'],['Salem','Tamil Nadu'],['Tiruchirappalli','Tamil Nadu'],['Kochi','Kerala'],['Munnar','Kerala'],['Thiruvananthapuram','Kerala'],['Kozhikode','Kerala'],['Bengaluru','Karnataka'],['Mysuru','Karnataka'],['Mangaluru','Karnataka'],['Hubballi','Karnataka'],['Hyderabad','Telangana'],['Warangal','Telangana'],['Kolkata','West Bengal'],['Siliguri','West Bengal'],['Bhubaneswar','Odisha'],['Puri','Odisha'],['Patna','Bihar'],['Gaya','Bihar'],['Ranchi','Jharkhand'],['Raipur','Chhattisgarh'],['Bhopal','Madhya Pradesh'],['Indore','Madhya Pradesh'],['Shimla','Himachal Pradesh'],['Manali','Himachal Pradesh'],['Dharamshala','Himachal Pradesh'],['Amritsar','Punjab'],['Chandigarh','Chandigarh'],['Srinagar','Jammu & Kashmir'],['Jammu','Jammu & Kashmir'],['Leh','Ladakh'],['Goa','Goa'],['Panaji','Goa'],['Guwahati','Assam'],['Shillong','Meghalaya'],['Gangtok','Sikkim']
].map(([name,state])=>({placeId:`fallback:${name.toLowerCase().replace(/[^a-z0-9]+/g,'-')}`,displayName:name,formattedAddress:`${name}, ${state}, India`,primaryText:name,secondaryText:`${state}, India`,types:['locality'],fallback:true}));
const normalise=v=>(v||'').toString().toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').trim();
const escapeHtml=s=>(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const state={route:null,locations:{},vehicles:{}};
const defaultHaridwar={placeId:'fallback:haridwar',displayName:'Haridwar',primaryText:'Haridwar',secondaryText:'Uttarakhand, India',formattedAddress:'Haridwar, Uttarakhand, India',fallback:true};
const api=async body=>{if(!MAPS_ENDPOINT)throw Error('Maps proxy not configured');const r=await fetch(MAPS_ENDPOINT,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});if(!r.ok)throw Error('Maps proxy '+r.status);return r.json()};
const fallbackSearch=input=>{const n=normalise(input);return fallbackLocations.filter(x=>normalise(`${x.primaryText} ${x.secondaryText}`).includes(n)).slice(0,7)};
const vehicleSearch=input=>{const n=normalise(input);return vehicleCatalog.filter(v=>v.active&&(!n||normalise([v.full_name,v.manufacturer,v.model,v.category,...v.aliases].join(' ')).includes(n))).slice(0,8)};
const renderLocation=x=>`<span class="hyt-suggestion-icon">⌖</span><span><strong>${escapeHtml(x.primaryText||x.displayName)}</strong><small>${escapeHtml(x.secondaryText||x.formattedAddress||'India')}</small></span>`;
const renderVehicle=x=>`<span class="hyt-suggestion-icon">🚐</span><span><strong>${escapeHtml(x.full_name)}</strong><small>${escapeHtml(x.category)} · ${x.seating_capacity} Seater · ₹${x.per_km_rate}/km</small></span>`;
function setupAutocomplete(inputId,listId,type,onSelect){
 const input=q('#'+inputId),list=q('#'+listId);if(!input||!list)return;let items=[],active=-1,seq=0,token=crypto?.randomUUID?.()||String(Date.now());
 const render=(arr,loading=false)=>{items=arr;active=-1;list.innerHTML=loading?'<div class="hyt-suggestion-state">Searching India…</div>':arr.length?arr.map((x,i)=>`<button type="button" class="hyt-suggestion" role="option" data-i="${i}">${type==='vehicle'?renderVehicle(x):renderLocation(x)}</button>`).join(''):'<div class="hyt-suggestion-state">No matching locations found. Try a city, landmark or state.</div>';list.classList.toggle('open',loading||arr.length>0||!!input.value.trim());input.setAttribute('aria-expanded',String(list.classList.contains('open')))};
 const choose=async item=>{input.value=type==='vehicle'?item.full_name:(item.displayName||item.primaryText);list.classList.remove('open');input.setAttribute('aria-expanded','false');if(type==='vehicle'){state.vehicles[inputId]=item;onSelect?.(item);return}let selected=item;if(!item.fallback&&item.placeId&&!item.lat){try{selected={...item,...await api({action:'details',placeId:item.placeId,sessionToken:token})}}catch(e){console.warn('Place details unavailable',e)}}state.locations[inputId]=selected;onSelect?.(selected)};
 input.addEventListener('input',async()=>{const value=input.value.trim();const id=++seq;if(!value){render(type==='vehicle'?vehicleSearch(''):fallbackSearch(''));return}render([],true);if(type==='vehicle'){render(vehicleSearch(value));return}const fallback=fallbackSearch(value);if(!MAPS_ENDPOINT){render(fallback);return}try{const data=await api({action:'autocomplete',input:value,sessionToken:token});if(id!==seq)return;const live=(data.suggestions||[]).map(s=>s.placePrediction).filter(Boolean).map(p=>({placeId:p.placeId,displayName:p.text?.text||p.structuredFormat?.mainText?.text||'',primaryText:p.structuredFormat?.mainText?.text||p.text?.text||'',secondaryText:p.structuredFormat?.secondaryText?.text||'',formattedAddress:p.text?.text||'',types:p.types||[],fallback:false}));render([...live,...fallback.filter(f=>!live.some(l=>normalise(l.primaryText)===normalise(f.primaryText)))].slice(0,8))}catch(e){if(id===seq)render(fallback)}}); 
 input.addEventListener('focus',()=>{if(!input.value.trim())render(type==='vehicle'?vehicleSearch(''):fallbackSearch(''))});
 input.addEventListener('keydown',e=>{if(!list.classList.contains('open'))return;if(e.key==='ArrowDown'){e.preventDefault();active=Math.min(active+1,items.length-1)}else if(e.key==='ArrowUp'){e.preventDefault();active=Math.max(active-1,0)}else if(e.key==='Enter'&&active>=0){e.preventDefault();choose(items[active])}else if(e.key==='Escape'){list.classList.remove('open');return}qa('.hyt-suggestion',list).forEach((b,i)=>b.classList.toggle('active',i===active))});
 list.addEventListener('mousedown',e=>{const b=e.target.closest('.hyt-suggestion');if(b){e.preventDefault();choose(items[Number(b.dataset.i)])}});
 document.addEventListener('click',e=>{if(!input.closest('.hyt-autocomplete')?.contains(e.target))list.classList.remove('open')});
}
const setLoc=(id,x)=>{const el=q('#'+id);if(el)el.value=x.displayName||x.primaryText;state.locations[id]=x};
const setVeh=(id,x)=>{const el=q('#'+id);if(el)el.value=x.full_name;state.vehicles[id]=x};
const veh=id=>state.vehicles[id]||vehicleCatalog.find(v=>v.id===q('#'+id)?.value)||vehicleCatalog[1];
setupAutocomplete('hytFrom','hytFromSuggestions','location',x=>{setLoc('hytFrom',x);q('#hytRouteStatus')&&(q('#hytRouteStatus').textContent='From selected · choose a destination')});
setupAutocomplete('hytDestInput','hytToSuggestions','location',x=>{setLoc('hytDestInput',x);q('#hytDest')&&(q('#hytDest').value=x.placeId);q('#hytRouteStatus')&&(q('#hytRouteStatus').textContent='Destination selected · route ready to calculate')});
setupAutocomplete('hytVehicleInput','hytVehicleSuggestions','vehicle',x=>{setVeh('hytVehicleInput',x);q('#hytVehicle')&&(q('#hytVehicle').value=x.id)});
setupAutocomplete('hytPlannerFromInput','hytPlannerFromSuggestions','location',x=>setLoc('hytPlannerFromInput',x));
setupAutocomplete('hytPlannerDestInput','hytPlannerDestSuggestions','location',x=>setLoc('hytPlannerDestInput',x));
setupAutocomplete('hytPlannerVehicleInput','hytPlannerVehicleSuggestions','vehicle',x=>setVeh('hytPlannerVehicleInput',x));
setLoc('hytFrom',defaultHaridwar);setLoc('hytPlannerFromInput',defaultHaridwar);setVeh('hytVehicleInput',vehicleCatalog[1]);setVeh('hytPlannerVehicleInput',vehicleCatalog[1]);
const legacyDistance=(from,to)=>{if(normalise(from?.primaryText||from?.displayName)!=='haridwar')return null;const k=Object.keys(legacyNames).find(k=>normalise(legacyNames[k])===normalise(to?.primaryText||to?.displayName));return k?legacyKm[k]:null};
const formatDuration=s=>{if(!s)return '—';const m=Math.round(s/60),h=Math.floor(m/60),mm=m%60;return h?`${h} hr${h===1?'':'s'}${mm?` ${mm} min`:''}`:`${mm} min`};
const fareFor=(distance,v,trip)=>{if(!distance||!v)return null;const km=trip==='round'?distance*2:distance,driver=trip==='round'?3500:2200,toll=Math.round(km*.65/10)*10,parking=700,base=km*v.per_km_rate,total=Math.max(v.minimum_booking_rate,Math.round((base+driver+toll+parking)/500)*500);return{distance:km,oneWayDistance:distance,base,driver,toll,parking,total}};
function setResult(from,to,v,trip,route){const fare=route?.distanceKm?fareFor(route.distanceKm,v,trip):null;state.route={from,to,vehicle:v,tripType:trip,route,fare};q('#hytRouteTitle')&&(q('#hytRouteTitle').textContent=`${from.displayName||from.primaryText} → ${to.displayName||to.primaryText}${trip==='round'?' → '+(from.displayName||from.primaryText):''}`);q('#hytVehicleText')&&(q('#hytVehicleText').textContent=v.full_name);q('#hytKm')&&(q('#hytKm').textContent=fare?`${fare.distance.toLocaleString('en-IN')} km`:'—');q('#hytDays')&&(q('#hytDays').textContent=route?.durationSeconds?formatDuration(route.durationSeconds):'—');q('#hytFare')&&(q('#hytFare').textContent=fare?'₹'+fare.total.toLocaleString('en-IN'):'—');q('#hytFareInput')&&(q('#hytFareInput').value=fare?.total||'');q('#hytDriver')&&(q('#hytDriver').textContent=fare?'₹'+fare.driver.toLocaleString('en-IN'):'Included');q('#hytTollParking')&&(q('#hytTollParking').textContent=fare?'₹'+(fare.toll+fare.parking).toLocaleString('en-IN'):'—');return fare}
async function calculateTrip({from,to,vehicle,tripType,statusEl}){if(statusEl)statusEl.textContent='Calculating route…';let route=null;if(MAPS_ENDPOINT&&from?.placeId&&!from.fallback&&to?.placeId&&!to.fallback){try{route=await api({action:'route',origin:{placeId:from.placeId,lat:from.lat,lng:from.lng},destination:{placeId:to.placeId,lat:to.lat,lng:to.lng}})}catch(e){console.warn('Route API unavailable',e)}}if(!route){const km=legacyDistance(from,to);if(km)route={distanceKm:km,durationSeconds:null,source:'legacy-fallback'}}if(!route){state.route={from,to,vehicle,tripType,route:null,fare:null};q('#hytRouteTitle')&&(q('#hytRouteTitle').textContent=`${from.displayName||'From'} → ${to.displayName||'Destination'}`);q('#hytKm')&&(q('#hytKm').textContent='—');q('#hytDays')&&(q('#hytDays').textContent='—');q('#hytFare')&&(q('#hytFare').textContent='—');q('#hytFareInput')&&(q('#hytFareInput').value='');if(statusEl)statusEl.textContent='Estimated route unavailable — contact travel desk for quote.';return null}const fare=setResult(from,to,vehicle,tripType,route);if(statusEl)statusEl.textContent=route.source==='legacy-fallback'?'Using existing Haridwar route benchmark.':'Live route calculated.';return fare}
q('#hytFareForm')?.addEventListener('submit',async e=>{e.preventDefault();const from=state.locations.hytFrom||defaultHaridwar,to=state.locations.hytDestInput;if(!to){q('#hytRouteStatus')&&(q('#hytRouteStatus').textContent='Select a destination from the suggestions first.');return}await calculateTrip({from,to,vehicle:veh('hytVehicleInput'),tripType:q('#hytQuickReturn')?.value||'round',statusEl:q('#hytRouteStatus')});q('#hytResult')?.scrollIntoView({behavior:'smooth',block:'center'})});
q('#hytBuild')?.addEventListener('click',async()=>{const from=state.locations.hytPlannerFromInput||defaultHaridwar,to=state.locations.hytPlannerDestInput;if(!to){q('#hytRouteStatus')&&(q('#hytRouteStatus').textContent='Select a destination from the suggestions first.');return}const trip=q('#hytPlannerReturn')?.value||'round';q('#hytPassengers')&&(q('#hytPassengers').value=q('#hytPlannerPassengers')?.value||6);q('#hytQuickReturn')&&(q('#hytQuickReturn').value=trip);await calculateTrip({from,to,vehicle:veh('hytPlannerVehicleInput'),tripType:trip,statusEl:q('#hytRouteStatus')});q('#hytResult')?.scrollIntoView({behavior:'smooth',block:'center'})});
q('#hytBook')?.addEventListener('click',()=>q('#booking')?.scrollIntoView({behavior:'smooth',block:'center'}));
q('#hytCustomerForm')?.addEventListener('submit',e=>{e.preventDefault();const r=state.route,code='HYT'+Date.now().toString().slice(-6),date=q('#hytCustomerDate')?.value||q('#hytTravelDate')?.value||'Not selected',msg=`Hi Aswal Tour & Travels,

I want to book a trip.

Booking ID: ${code}
Customer Name: ${q('#hytCustomerName')?.value||'Not provided'}
Mobile: ${q('#hytCustomerMobile')?.value||'Not provided'}
From: ${r?.from?.formattedAddress||r?.from?.displayName||'Not selected'}
To: ${r?.to?.formattedAddress||r?.to?.displayName||'Not selected'}
Travel Date: ${date}
Passengers: ${q('#hytPassengers')?.value||'Not provided'}
Vehicle: ${r?.vehicle?.full_name||'Not selected'}
Trip Type: ${r?.tripType==='round'?'Round Trip':'One Way'}
Estimated Distance: ${r?.fare?.distance?`${r.fare.distance.toLocaleString('en-IN')} km`:'Route unavailable'}
Estimated Fare: ${r?.fare?.total?'₹'+r.fare.total.toLocaleString('en-IN'):'Quote required'}

Please confirm availability and final fare.`;q('#hytBookingNote')&&(q('#hytBookingNote').textContent=`Booking ${code} prepared. Opening WhatsApp with the complete trip summary…`);localStorage.setItem('aswal_last_booking',JSON.stringify({code,name:q('#hytCustomerName')?.value,mobile:q('#hytCustomerMobile')?.value,route:q('#hytRouteTitle')?.textContent,vehicle:r?.vehicle?.full_name||'',fare:r?.fare?.total||null,date}));window.open('https://wa.me/917983558954?text='+encodeURIComponent(msg),'_blank')});
q('#hytMenu')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));
const wa=document.createElement('a');wa.className='hyt-wa-float';wa.href='https://wa.me/917983558954?text='+encodeURIComponent('Hi Aswal Tour & Travels, I have a travel query.');wa.target='_blank';wa.rel='noopener noreferrer';wa.setAttribute('aria-label','WhatsApp Aswal Tour & Travels');wa.innerHTML='<span aria-hidden="true">💬</span><b>WhatsApp</b>';document.body.appendChild(wa);
document.head.insertAdjacentHTML('beforeend','<style>.hyt-wa-float{position:fixed;right:22px;bottom:22px;z-index:9999;width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#25D366;color:#062015;box-shadow:0 14px 35px #0004;border:3px solid #fff;text-decoration:none;transition:.3s}.hyt-wa-float:hover{transform:translateY(-5px) scale(1.05)}.hyt-wa-float b{position:absolute;right:62px;white-space:nowrap;background:#07131f;color:#fff;padding:8px 11px;border-radius:999px;font:800 9px Manrope;opacity:0;transform:translateX(8px);transition:.3s}.hyt-wa-float:hover b{opacity:1;transform:none}@media(max-width:560px){.hyt-wa-float{right:14px;bottom:14px;width:48px;height:48px}}</style>');
})();
// ASWAL JOURNEY NAVIGATOR
const aswalSections=[...document.querySelectorAll('.hyt-hero,#services,#planner,#destinations,#pages,#trust,#contact,#booking')];
const aswalNames=['HOME','SERVICES','PLAN MY TRIP','DESTINATIONS','ALL PAGES','WHY ASWAL','CONTACT','BOOKING'];
const aswalRail=document.createElement('div');
aswalRail.className='aswal-journey-rail';
aswalRail.innerHTML='<div class="aswal-current">HOME</div><div class="aswal-dots">'+aswalNames.map((n,i)=>'<button type="button" data-i="'+i+'" title="'+n+'"></button>').join('')+'</div>';
document.body.appendChild(aswalRail);
const aswalDots=[...aswalRail.querySelectorAll('button')],aswalCurrent=aswalRail.querySelector('.aswal-current');
function aswalSet(i){aswalCurrent.textContent=aswalNames[i];aswalDots.forEach((d,n)=>d.classList.toggle('active',n===i))}
aswalDots.forEach((d,i)=>d.onclick=()=>aswalSections[i]?.scrollIntoView({behavior:'smooth',block:'start'}));
new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=aswalSections.indexOf(e.target);if(i>-1)aswalSet(i)}}),{rootMargin:'-45% 0px -45% 0px'}).observe(aswalSections[0]);
aswalSections.slice(1).forEach(el=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)aswalSet(aswalSections.indexOf(e.target))}),{rootMargin:'-45% 0px -45% 0px'}).observe(el));
const aswalBar=document.createElement('div');aswalBar.className='aswal-scroll-bar';document.body.appendChild(aswalBar);
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;aswalBar.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
const aswalOverlay=document.createElement('div');aswalOverlay.className='aswal-page-switch';aswalOverlay.innerHTML='<div><small>ASWAL TOUR & TRAVELS</small><strong id="aswalSwitchName">Opening…</strong><span></span></div>';document.body.appendChild(aswalOverlay);
document.querySelectorAll('a[href$=".html"],a[href*=".html#"]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(!href||href.startsWith('index.html'))return;const name=(a.querySelector('h3')?.textContent||a.textContent||href).replace(/\s+/g,' ').trim();document.querySelector('#aswalSwitchName').textContent=name;aswalOverlay.classList.add('show');setTimeout(()=>location.href=href,450)}));
aswalSet(0);

})();