(()=>{const q=s=>document.querySelector(s);const nav=q('#hytNav');addEventListener('scroll',()=>nav?.classList.toggle('scrolled',scrollY>40),{passive:true});
const rates={sedan:15,suv:19,innova:23,crysta:27,'9':32,'12':35,'16':38,'17':40,'20':44};const km={kedarnath:410,badrinath:325,yamunotri:230,gangotri:290,vrindavan:250,delhi:220,ayodhya:550,varanasi:700,jaipur:600};const names={kedarnath:'Kedarnath',badrinath:'Badrinath',yamunotri:'Yamunotri',gangotri:'Gangotri',vrindavan:'Vrindavan',delhi:'Delhi',ayodhya:'Ayodhya',varanasi:'Varanasi',jaipur:'Jaipur',chardham:'Char Dham'};
const key=v=>(v||'').toLowerCase().replace(/\s+/g,'');const vehicleKey=v=>{const s=(v||'').toLowerCase();return s.includes('12')?'12':s.includes('9')?'9':s.includes('16')?'16':s.includes('17')?'17':s.includes('20')?'20':s.includes('crysta')?'crysta':s.includes('innova')?'innova':s.includes('suv')?'suv':'sedan'};
function calculate(){const d=q('#hytDest')?.value||'kedarnath',v=q('#hytVehicle')?.value||'12',ret=(q('#hytQuickReturn')?.value||'round')==='round';let distance=(km[d]||d==='chardham')?(km[d]||1000):400;if(ret)distance*=2;const driver=ret?3500:2200,toll=Math.round(distance*.65/10)*10,parking=700,base=distance*(rates[v]||35),total=Math.round((base+driver+toll+parking)/500)*500; if(q('#hytRouteTitle'))q('#hytRouteTitle').textContent='Haridwar → '+(names[d]||'Your Destination')+(ret?' → Haridwar':'');if(q('#hytDays'))q('#hytDays').textContent=ret?(d==='chardham'?'8–10 Days':'4–6 Days'):'2–4 Days';if(q('#hytKm'))q('#hytKm').textContent=distance.toLocaleString('en-IN')+' km';if(q('#hytVehicleText'))q('#hytVehicleText').textContent=v==='sedan'?'Sedan':v==='suv'?'SUV':v==='innova'?'Innova':v==='crysta'?'Innova Crysta':v+' Seater Traveller';if(q('#hytFare'))q('#hytFare').textContent='₹'+total.toLocaleString('en-IN');return total}
['hytDest','hytVehicle','hytPassengers','hytQuickReturn'].forEach(id=>q('#'+id)?.addEventListener('change',calculate));calculate();
q('#hytFareForm')?.addEventListener('submit',e=>{e.preventDefault();calculate();q('#hytResult')?.scrollIntoView({behavior:'smooth',block:'center'})});
q('#hytBuild')?.addEventListener('click',()=>{q('#hytDest').value=key(q('#hytPlannerDest').value)==='chardham'?'chardham':key(q('#hytPlannerDest').value);q('#hytVehicle').value=vehicleKey(q('#hytPlannerVehicle').value);q('#hytPassengers').value=q('#hytPlannerPassengers').value;q('#hytQuickReturn').value=q('#hytPlannerReturn').value;calculate();q('#hytResult')?.scrollIntoView({behavior:'smooth',block:'center'})});
q('#hytBook')?.addEventListener('click',()=>q('#booking')?.scrollIntoView({behavior:'smooth',block:'center'}));
q('#hytCustomerForm')?.addEventListener('submit',e=>{e.preventDefault();calculate();const code='HYT'+Date.now().toString().slice(-6),msg='Hi Aswal Tour & Travels, I want to book a yatra. Booking ID: '+code+'. Route: '+q('#hytRouteTitle').textContent+'. Vehicle: '+q('#hytVehicleText').textContent+'. Estimated fare: '+q('#hytFare').textContent+'. Passengers: '+q('#hytPassengers').value+'. Please confirm availability and advance payment details.';const note=q('#hytBookingNote');if(note)note.textContent='Booking '+code+' created locally. Opening WhatsApp with your trip summary…';localStorage.setItem('aswal_last_booking',JSON.stringify({code,name:q('#hytCustomerName').value,mobile:q('#hytCustomerMobile').value,route:q('#hytRouteTitle').textContent,vehicle:q('#hytVehicleText').textContent,fare:q('#hytFare').textContent,date:q('#hytCustomerDate')?.value||q('#hytTravelDate')?.value||''}));window.open('https://wa.me/917983558954?text='+encodeURIComponent(msg+' Customer: '+q('#hytCustomerName').value+'. Mobile: '+q('#hytCustomerMobile').value+'. Travel date: '+(q('#hytCustomerDate')?.value||q('#hytTravelDate')?.value||'Not selected')+'. Notes: '+(q('#hytCustomerNotes')?.value||'None')+'.'),'_blank')});
q('#hytMenu')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));
const wa=document.createElement('a');wa.className='hyt-wa-float';wa.href='https://wa.me/917983558954?text='+encodeURIComponent('Hi Aswal Tour & Travels, I have a travel query.');wa.target='_blank';wa.rel='noopener noreferrer';wa.setAttribute('aria-label','WhatsApp Aswal Tour & Travels');wa.innerHTML='<span aria-hidden="true"><svg viewBox="0 0 24 24" width="20" height="20" fill="currentColor"><path d="M20.5 3.5A11.8 11.8 0 0 0 12.1 0C5.6 0 .3 5.3.3 11.8c0 2.1.6 4.1 1.6 5.9L.2 24l6.5-1.7c1.7.9 3.5 1.3 5.4 1.3h.1c6.5 0 11.8-5.3 11.8-11.8 0-3.2-1.3-6.1-3.5-8.3Zm-8.4 18.1h-.1c-1.7 0-3.4-.5-4.9-1.3l-.4-.2-3.9 1 1-3.8-.2-.4a9.8 9.8 0 1 1 8.5 4.7Zm5.4-7.4c-.3-.2-1.8-.9-2.1-1-.3-.1-.5-.2-.7.2-.2.3-.8 1-.9 1.2-.2.2-.3.2-.6.1-1.7-.8-2.8-1.5-3.9-3.4-.3-.5.3-.5.8-1.6.1-.2.1-.4 0-.6l-.9-2.1c-.2-.6-.5-.5-.7-.5h-.6c-.2 0-.6.1-.9.4-.3.3-1.1 1-1.1 2.5s1.1 2.9 1.2 3.1c.2.2 2.1 3.3 5.1 4.6.7.3 1.3.5 1.7.6.7.2 1.4.2 1.9.1.6-.1 1.8-.7 2-1.4.3-.7.3-1.3.2-1.4-.1-.1-.3-.2-.6-.3Z"/></svg></span><b>WhatsApp</b>';
document.head.insertAdjacentHTML('beforeend','<style>.hyt-wa-float{position:fixed;right:22px;bottom:22px;z-index:9999;width:52px;height:52px;border-radius:50%;display:grid;place-items:center;background:#25D366;color:#062015;box-shadow:0 14px 35px #0004;border:3px solid #fff;text-decoration:none;transition:.3s}.hyt-wa-float:hover{transform:translateY(-5px) scale(1.05)}.hyt-wa-float b{position:absolute;right:62px;white-space:nowrap;background:#07131f;color:#fff;padding:8px 11px;border-radius:999px;font:800 9px Manrope;opacity:0;transform:translateX(8px);transition:.3s}.hyt-wa-float:hover b{opacity:1;transform:none}@media(max-width:560px){.hyt-wa-float{right:14px;bottom:14px;width:48px;height:48px}}</style>');document.body.appendChild(wa);

// ASWAL JOURNEY NAVIGATOR
const aswalSections=[...document.querySelectorAll('.hyt-hero,#services,#planner,#destinations,#pages,#trust,#contact,#booking')];
const aswalNames=['HOME','SERVICES','PLAN MY TRIP','DESTINATIONS','ALL PAGES','WHY ASWAL','CONTACT','BOOKING'];
const aswalRail=document.createElement('div');
aswalRail.className='aswal-journey-rail';
aswalRail.innerHTML='<div class="aswal-current">HOME</div><div class="aswal-dots">'+aswalNames.map((n,i)=>'<button type="button" data-i="'+i+'" title="'+n+'"></button>').join('')+'</div>';
document.body.appendChild(aswalRail);
const aswalDots=[...aswalRail.querySelectorAll('button')],aswalCurrent=aswalRail.querySelector('.aswal-current');
function aswalSet(i){aswalCurrent.textContent=aswalNames[i];aswalDots.forEach((d,n)=>d.classList.toggle('active',n===i))}
aswalDots.forEach((d,i)=>d.onclick=()=>aswalSections[i]?.scrollIntoView({behavior:'smooth',block:'start'}));
new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){const i=aswalSections.indexOf(e.target);if(i>-1)aswalSet(i)}}),{rootMargin:'-45% 0px -45% 0px'}).observe(aswalSections[0]);
aswalSections.slice(1).forEach(el=>new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting)aswalSet(aswalSections.indexOf(e.target))}),{rootMargin:'-45% 0px -45% 0px'}).observe(el));
const aswalBar=document.createElement('div');aswalBar.className='aswal-scroll-bar';document.body.appendChild(aswalBar);
addEventListener('scroll',()=>{const max=document.documentElement.scrollHeight-innerHeight;aswalBar.style.width=(max?scrollY/max*100:0)+'%'},{passive:true});
const aswalOverlay=document.createElement('div');aswalOverlay.className='aswal-page-switch';aswalOverlay.innerHTML='<div><small>ASWAL TOUR & TRAVELS</small><strong id="aswalSwitchName">Opening…</strong><span></span></div>';document.body.appendChild(aswalOverlay);
document.querySelectorAll('a[href$=".html"],a[href*=".html#"]').forEach(a=>a.addEventListener('click',e=>{const href=a.getAttribute('href');if(!href||href.startsWith('index.html'))return;const name=(a.querySelector('h3')?.textContent||a.textContent||href).replace(/\s+/g,' ').trim();document.querySelector('#aswalSwitchName').textContent=name;aswalOverlay.classList.add('show');setTimeout(()=>location.href=href,450)}));
aswalSet(0);

})();