-- ASWAL TOUR & TRAVELS — production database blueprint
create extension if not exists pgcrypto;
create table if not exists destinations(id uuid primary key default gen_random_uuid(),name text not null,region text,slug text unique not null,distance_from_haridwar_km integer,active boolean default true);
create table if not exists vehicles(id uuid primary key default gen_random_uuid(),name text not null,type text not null,seats integer,rate_per_km numeric(10,2),base_fare numeric(10,2) default 0,active boolean default true);
create table if not exists drivers(id uuid primary key default gen_random_uuid(),name text not null,mobile text not null,license_no text,license_verified boolean default false,vehicle_id uuid references vehicles(id),active boolean default true);
create table if not exists packages(id uuid primary key default gen_random_uuid(),name text not null,slug text unique not null,duration_days integer,duration_nights integer,base_price numeric(12,2),description text,active boolean default true);
create table if not exists bookings(id uuid primary key default gen_random_uuid(),booking_code text unique not null,customer_name text not null,mobile text not null,email text,from_city text default 'Haridwar',destination text not null,travel_date date,return_date date,passengers integer,vehicle_id uuid references vehicles(id),driver_id uuid references drivers(id),distance_km integer,base_fare numeric(12,2),driver_charge numeric(12,2),toll numeric(12,2),parking numeric(12,2),discount numeric(12,2) default 0,total_fare numeric(12,2),advance_paid numeric(12,2) default 0,status text default 'pending',payment_status text default 'unpaid',notes text,created_at timestamptz default now());
create table if not exists vehicle_availability(id uuid primary key default gen_random_uuid(),vehicle_id uuid references vehicles(id) on delete cascade,blocked_from date,blocked_to date,reason text);
create table if not exists reviews(id uuid primary key default gen_random_uuid(),customer_name text,rating integer check(rating between 1 and 5),review text,approved boolean default false,created_at timestamptz default now());
create index if not exists bookings_date_idx on bookings(travel_date); create index if not exists bookings_status_idx on bookings(status); create index if not exists vehicles_active_idx on vehicles(active);